from __future__ import annotations

APP_VERSION = "35.2.8"
RELEASE_ID = "R35_2_8_CONCISE_SOURCE_FALLBACK"
ASSET_VERSION = "R35_2_8"
INGESTION_VERSION = 6
ANSWER_CACHE_NAMESPACE_DEFAULT = "barsan-r35-2-8-concise-source-fallback"
SCHEMA_REVISION = "r35.2.8-001"
