from __future__ import annotations

APP_VERSION = "35.2.4"
RELEASE_ID = "R35_2_4_SEMANTIC_SOURCE_REASONING"
ASSET_VERSION = "R35_2_4"
INGESTION_VERSION = 6
ANSWER_CACHE_NAMESPACE_DEFAULT = "barsan-r35-2-4-semantic-source-reasoning"
SCHEMA_REVISION = "r35.2.4-001"
